### ISSUE TITLE
Error loading shared library

### ISSUE THREAD

**Issue by Yggdrasil** [lkwg82/h2o.docker#1]
I wanted to try out H2O via the docker image. Unfortunately it won't start for me and outputs the below errors. The container exits immediately after this.

The image id at this time is _d6b4c9ab9577_.

> ❯ docker run -p "8080:80" -ti lkwg82/h2o-http2-server
> Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/bin/h2o)
> Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/h2o)
> Error relocating /usr/local/bin/h2o: _ZnwmRKSt9nothrow_t: symbol not found
> Error relocating /usr/local/bin/h2o: _ZdaPv: symbol not found
> Error relocating /usr/local/bin/h2o: _Znwm: symbol not found
> Error relocating /usr/local/bin/h2o: _ZSt20__throw_length_errorPKc: symbol not found
> Error relocating /usr/local/bin/h2o: _ZdlPv: symbol not found
> Error relocating /usr/local/bin/h2o: _Znam: symbol not found
> Error relocating /usr/local/bin/h2o: __gxx_personality_v0: symbol not found
> Error relocating /usr/local/bin/h2o: _ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS_: symbol not found
> Error relocating /usr/local/bin/h2o: _ZSt17__throw_bad_allocv: symbol not found
> Error relocating /usr/local/bin/h2o: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm: symbol not found
> Error relocating /usr/local/bin/h2o: _ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base: symbol not found
> Error relocating /usr/local/bin/h2o: _ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base: symbol not found
> Error relocating /usr/local/bin/h2o: _Unwind_Resume: symbol not found
> Error relocating /usr/local/bin/h2o: _ZdlPvRKSt9nothrow_t: symbol not found
> Error relocating /usr/local/bin/h2o: _ZTVN10__cxxabiv117__class_type_infoE: symbol not found
> Error relocating /usr/local/bin/h2o: _ZTVN10__cxxabiv117__class_type_infoE: symbol not found
> Error relocating /usr/local/bin/h2o: _ZTVN10__cxxabiv120__si_class_type_infoE: symbol not found
> Error relocating /usr/local/bin/h2o: _ZTVN10__cxxabiv120__si_class_type_infoE: symbol not found
> Error relocating /usr/local/bin/h2o: _ZTVN10__cxxabiv120__si_class_type_infoE: symbol not found
> Error relocating /usr/local/bin/h2o: _ZTVN10__cxxabiv120__si_class_type_infoE: symbol not found
> Error relocating /usr/local/bin/h2o: _ZTVN10__cxxabiv120__si_class_type_infoE: symbol not found
> Error relocating /usr/local/bin/h2o: __gxx_personality_v0: symbol not found
> Error relocating /usr/local/bin/h2o: _ZSt7nothrow: symbol not found

Thanks, Martijn

**Comment by lkwg82** [comment]
I'll take a look into it.

**Comment by Yggdrasil** [comment]
Good job! Thanks a lot!
