### ISSUE TITLE
mruby support?

### ISSUE THREAD

**Issue by ghost** [lkwg82/h2o.docker#2]
It seems I can't run mruby scripts in this docker image. Will it be better to create a new variant which supports mruby or add it to this one?
```
web_1  | [h2o.conf:8] unknown command: mruby.handler
```
cmake -DWITH_MRUBY=ON .

**Comment by lkwg82** [comment]
Oh I was not aware of that. I'll have a look into.

**Comment by lkwg82** [comment]
I think it is ok to add it here. I'll accept a PR.
