### ISSUE TITLE
Dockerfile Not Working

### ISSUE THREAD

**Issue by HaydnTrigg** [lkwg82/h2o.docker#3]
Does not work: https://github.com/lkwg82/h2o.docker/blob/v2.1.0/Dockerfile

Error: could not open configuration file etc/h2o.conf: No such file or directory

This verison works: https://github.com/lkwg82/h2o.docker/blob/v2.0.6/Dockerfile

**Comment by lkwg82** [comment]
What did you do?

**Comment by lkwg82** [comment]
close due to age
