### ISSUE TITLE
tags/v2.3.0-beta1 not found in docker hub 

### ISSUE THREAD

**Issue by y-yagi** [lkwg82/h2o.docker#6]
Hi. 

It seems `tags/v2.3.0-beta1` was committed in 88e29b5618497d6ecc7f74775655cff6bada5eb6. 
But that version not found in docker hub. 
https://hub.docker.com/r/lkwg82/h2o-http2-server/tags/ 

Is this intentional?  Thanks!

**Comment by lkwg82** [comment]
As I remember, it is been little more than a year that I interacted with the project, each committed version is intended to be pushed to docker hub.

So short answer: no.

But maybe you can offer a fixed version as PR, if u like.

**Comment by y-yagi** [comment]
Thanks for your quick response! 

I understood that this is not intentional. I will try to fix. Thanks!
