### ISSUE TITLE
Adding H2O to the Docker Official Images program

### ISSUE THREAD

**Issue by bardiharborow** [lkwg82/h2o.docker#7]
I'm just wondering if you would consider blessing/participating in a request to add H2O to the [Docker Official Images program](https://github.com/docker-library/official-images). I have begun work on a Dockerfile that should meet their requirements, which is attached below. Perhaps you could provide feedback?

[edit: older Dockerfile removed]

**Comment by lkwg82** [comment]
good idea

**Comment by bardiharborow** [comment]
@kazuho if you get a moment, could you take a look at [the Dockerfile](https://github.com/bardiharborow/docker-h2o/blob/master/Dockerfile) and let me know if you're okay with me pursing official image inclusion?

**Comment by bardiharborow** [comment]
Closing in favor of a h2o/h2o issue per Docker team guidance.

**Comment by lkwg82** [comment]
great!
